services:
  - type: web
    name: tictactoang
    env: docker
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: Data Source=/app/Data/tictactoang.db
    disk:
      name: tictactoang-data
      mountPath: /app/Data
      sizeGB: 1
