services:
  - type: web
    name: tictactoang
    runtime: docker
    autoDeploy: true
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Database__Provider
        value: Postgres
      - key: ConnectionStrings__DefaultConnection
        fromDatabase:
          name: tictactoang-db
          property: connectionString
      - key: Jwt__Key
        generateValue: true
      - key: Jwt__Issuer
        value: TicTacToang
      - key: Jwt__Audience
        value: TicTacToang.Client

databases:
  - name: tictactoang-db
    databaseName: tictactoang
    user: tictactoang
